//{{NO_DEPENDENCIES}}
// Plik do³¹czany wygenerowany przez œrodowisko Microsoft Visual C++.
// U¿ywany przez: WinRod.rc
//
#define IDC_MYICON                      2
#define IDOK2                           3
#define ID_LEV                          3
#define ID_DEFAULT                      3
#define ID_ARANGE                       3
#define IDC_ARANGE                      3
#define IDD_WINROD_DIALOG               102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    104
#define IDM_ABOUT                       105
#define IDM_EXIT                        106
#define IDI_WINROD                      107
#define IDC_WINROD                      109
#define IDR_MAINFRAME                   128
#define IDB_TOOLBAR                     134
#define ID_TOOLBAR                      135
#define IDB_BITMAP1                     136
#define IDB_TOOLBAR_WINDOWS             138
#define IDD_FIT                         139
#define IDD_SET                         140
#define IDD_DOMAINS                     141
#define IDD_CALC_PATTERSON              142
#define IDD_CALCULATE                   143
#define IDD_EL_DENS                     144
#define IDD_CONTUR_MAP                  145
#define IDD_KETTING                     146
#define IDB_BITMAP2                     147
#define IDB_TOOLBAR_MAIN                148
#define IDD_3D_SETTINGS                 149
#define IDD_2D_SETTINGS                 150
#define IDB_TOLBAR_BEGGINING            151
#define IDB_TOOLBAR_V                   152
#define IDB_BITMAP3                     153
#define ID_TOOLBAR_MAIN                 154
#define IDD_ASA_PROGRESS                155
#define ID_TOOLBAR_WINDOWS              156
#define IDD_SYMMETRY                    157
#define IDD_EDIT_FIT_FILE               158
#define IDD_EDIT_BULK_FILE              159
#define IDD_ATOM_PROPERITIES            160
#define IDB_TOOLBAR_EDIT                161
#define ID_TOOLBAR_EDIT                 162
#define IDD_EDIT_DATA_FILE              163
#define IDD_CHI_CONTUR                  164
#define IDD_ELECTRON_DENSITY_SETTINGS   165
#define ID_TOOLBAR_OPEN                 166
#define IDD_MOLECULAR_FIT               166
#define IDD_OPEN_DATA_POINTS            167
#define IDD_FIT_OPEN                    168
#define IDD_NEAR_BRAGG_INCREASE         169
#define IDD_EDIT_ENERGY                 170
#define IDD_CALCULATE_COEFFICIENTS      171
#define IDD_PLOT_COEFFICIENTS           172
#define IDD_MULTIPLOT                   173
#define IDD_ASA_SETTINKGS               174
#define IDD_DIALOG1                     175
#define IDD_OPTIONS                     175
#define IDR_CONTEXT_MENU                177
#define IDD_SCALE                       179
#define IDD_DATA_REDUCTION              180
#define IDD_DIALOG2                     181
#define IDD_SORT_BULK                   181
#define ID_TOOLBAR_3D0                  400
#define ID_TOOLBAR_3D1                  401
#define ID_TOOLBAR_3D2                  402
#define ID_TOOLBAR_3D3                  403
#define ID_TOOLBAR_CHI                  440
#define ID_TIMER                        499
#define ID_TIMER2                       500
#define IDC_COMBOBOX                    501
#define IDC_COMBOBOX2                   502
#define ID_TOOLBAR_HKL                  505
#define ID_TOOLBAR_RODS                 506
#define IDC_COMBOBOX_H                  510
#define IDC_COMBOBOX_K                  511
#define IDC_COMBOBOX_L                  512
#define IDC_COMBOBOX_RODS               513
#define ID_ASA                          1000
#define IDC_EDIT1                       1001
#define IDC_EDIT2                       1002
#define IDC_BUTTON1                     1003
#define IDC_EDIT9                       1003
#define IDC_EDIT4                       1004
#define IDC_EDIT5                       1005
#define IDC_EDIT13                      1005
#define IDC_EDIT3                       1006
#define IDC_EDIT14                      1006
#define IDC_BUTTON2                     1007
#define IDC_EDIT10                      1007
#define IDC_CHECK1                      1008
#define IDC_EDIT6                       1009
#define IDC_CHECK2                      1009
#define IDC_BUTTON3                     1010
#define IDC_CHECK3                      1010
#define IDC_EDIT7                       1011
#define IDC_BUTTON6                     1011
#define IDC_INDYVIDUAL_COLOR            1011
#define IDC_EDIT8                       1012
#define IDC_EDIT17                      1012
#define IDC_BUTTON4                     1013
#define IDC_CHECK5                      1013
#define IDC_EDIT18                      1013
#define IDC_BUTTON9                     1013
#define IDC_RADIO1                      1014
#define IDC_CHECK6                      1014
#define IDC_RADIO2                      1015
#define IDC_EDIT15                      1015
#define IDC_CHECK11                     1015
#define IDC_RADIO3                      1016
#define IDC_EDIT16                      1016
#define IDC_COMBO1                      1017
#define IDC_RADIO4                      1017
#define IDC_LIST1                       1018
#define ID_BACKGROUND                   1019
#define IDC_LIST3                       1019
#define IDC_LIGHT                       1020
#define IDC_TEXT                        1021
#define IDC_BUTTON5                     1022
#define IDC_COLOR_FRAME                 1023
#define IDC_BACKGROUND                  1024
#define IDC_RGB_LIGHT                   1025
#define IDC_RGB_TEXT                    1026
#define IDC_LIGHT_COLOR2                1026
#define IDC_PROGRESS1                   1027
#define IDC_COLOR                       1030
#define IDC_TEXT_COLOR                  1031
#define IDC_COLOR2                      1031
#define IDC_TAB1                        1032
#define IDC_COLOR3                      1032
#define IDC_LIST2                       1033
#define IDC_CHECK4                      1034
#define IDC_PICTURE                     1035
#define IDC_CHECK7                      1035
#define IDC_SLIDER1                     1036
#define IDC_SLIDER2                     1037
#define IDC_AUTO_LIMITS                 1038
#define IDC_SLIDER8                     1038
#define IDC_SLIDER4                     1039
#define IDC_CHECK8                      1039
#define IDC_RICHEDIT21                  1040
#define IDC_CHARGE_SCALE                1040
#define IDC_CALL                        1041
#define IDC_TEXT_SIZE                   1041
#define IDC_CHECK                       1042
#define IDC_COMBO2                      1044
#define IDC_COMBO4                      1046
#define IDC_COMBO5                      1047
#define IDC_COMBO3                      1048
#define IDC_CHECK9                      1052
#define IDC_CHECK10                     1053
#define IDC_SPLIT1                      1054
#define IDC_STATIC1                     1055
#define IDC_STATIC2                     1056
#define IDC_STATIC3                     1057
#define IDC_STATIC4                     1058
#define IDC_STATIC5                     1059
#define IDC_STATIC6                     1060
#define IDC_STATIC7                     1061
#define IDC_BUTTON7                     1062
#define IDC_BUTTON8                     1063
#define IDC_STATIC8                     1064
#define IDC_STATIC10                    1065
#define IDC_STATIC9                     1066
#define IDC_RGB_BACKGROUND              1124
#define IDC_LIGHT_COLOR                 1125
#define IDC_SLIDER3                     1138
#define IDC_SLIDER5                     1140
#define IDC_SLIDER6                     1141
#define IDC_SLIDER7                     1142
#define IDC_EDIT11                      1408
#define IDC_EDIT12                      1409
#define ID_FILE_OPEN                    32771
#define ID_FILE_SAVE                    32772
#define ID_CALC_ROD                     32773
#define ID_CALC_IN                      32774
#define ID_CALC_ELECTRONDENSITY         32775
#define ID_SET_DOMAINS                  32776
#define ID_SET_SETTINGS                 32777
#define ID_EDIT                         32778
#define ID_FILE_RESET                   32779
#define ID_FIT                          32780
#define ID_CALC_DISTANCE                32781
#define ID_CALC_ANGLE                   32782
#define ID_CALC_TORSIAN                 32783
#define ID_FILE_3DEXPORT                32784
#define ID_FOURIERMAPOF_PATTERSONOFEXPERIMENTALSTRUCTUREFACTORS 32785
#define ID_FOURIERMAPOF_PATTERSONOFCALCULATEDSTRUCTUREFACTORS 32786
#define ID_FOURIERMAPOF_ELECTRONDENSITYDIFFERENCEMAP 32787
#define ID_FOURIERMAPOF_ELECTRONDENSITYOFMODEL 32788
#define ID_SET_SYMETRY                  32789
#define ID_SET_SYMMETRY                 32790
#define ID_SET_KEATING                  32791
#define ID_EDIT_BULKFILE                32792
#define ID_EDIT_FITFILE                 32793
#define ID_EDIT_BULK_FILE               32794
#define ID_EDIT_FIT_FILE                32795
#define ID_EDIT_ATOMPROPERITIES         32796
#define ID_EDIT_DATFILE                 32797
#define ID_EDIT_DATA_FILE               32798
#define ID_CALC_CHICONTURMAP            32799
#define ID_FILE_PRINT                   32800
#define ID_FILE_IMPORT                  32801
#define ID_EDIT_EDITENERGY              32802
#define ID_EDIT_DISPERSIONENERGY        32803
#define ID_DISPERSIONENERGY_EDITE1      32804
#define ID_DISPERSIONENERGY_EDITF2      32805
#define ID_DISPERSIONENERGY_EDITF1      32806
#define ID_DISPERSIONENERGY_CALCULATECOEFFICIENTS 32807
#define ID_CALC_DISPERSIONCOEFICIENTS   32808
#define ID_PLOT_MULTIPLOT               32809
#define ID_SET_ASASETTINGS              32810
#define ID_EDIT_COPY3DTOCLIPOBARD       32811
#define ID_EDIT_REFRESH                 32812
#define ID_OPTIONS_OPTONS               32813
#define ID_WINDOWS                      32814
#define ID_WINDOWS_CASCADE              32815
#define ID_WINDOWS_CAFLE                32816
#define ID_WINDOWS_MINIATURES           32817
#define ID_WINDOWS_DEFAULT              32818
#define ID_DEFAULT_STYLE1               32819
#define ID_DEFAULT_STYLE2               32820
#define ID_DEFAULT_STYLE3               32821
#define ID_OPTIONS_3DOPTIONS            32822
#define IDD_OPTIONS3D                   32822
#define ID_TEST_TEST                    32823
#define ID_PLOT_DELETE                  32824
#define ID_POSITION_X                   32827
#define IDM_POSITION                    32828
#define ID_POSITION_                    32831
#define ID_POSITION_32832               32832
#define ID_POSITION_2                   32834
#define ID_POSITION_32835               32835
#define ID_POSITION_32836               32836
#define ID_PLOT_SETXSCALE               32837
#define ID_PLOT_SETYSCALE               32838
#define ID_PLOT_SETPOINT                32839
#define ID_PLOT_SETSCALE                32840
#define ID_CALC_SORTBULKATOM            32841
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        182
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1068
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
