
set
indexh 1
indexk 1
indexl 0.2

!Go to set symmetry menu 
set symmetry (null) return return 
!Go to set domain menu 
set domain 
ndomain      3 
matrix       1   1.0000   0.0000   0.0000   1.0000 
matrix       2  -0.5000   0.7500  -1.0000  -0.5000 
matrix       3  -0.5000  -0.7500   1.0000  -0.5000 
fractional   no 
equal        yes 
coherent     no 
return return 


read fit 2012_.fit
read bul 2012_.bul
read dat 2012_.dat
read par 2012_.par


fit loop 100
fit call
fit asa
fit end_loop




